--Q1
SELECT NOM, PRENOM
FROM ABONNE
WHERE VILLE='MONTPELLIER';

--Q2
SELECT *
FROM EXEMPLAIRE
WHERE CODE_PRET='EMPRUNTABLE';

--Q3
SELECT TITRE, CATEGORIE
FROM LIVRE
WHERE CATEGORIE<>'MEDECINE' AND CATEGORIE<>'SCIENCES' AND CATEGORIE<>'LOISIRS'
ORDER BY CATEGORIE;

--Q4
SELECT *
FROM EMPRUNT
WHERE D_RET_REEL IS NULL;

--Q5
SELECT NUM_EX, D_EMPRUNT
FROM ABONNE, EMPRUNT
WHERE ABONNE.NUM_AB = EMPRUNT.NUM_AB
AND NOM='DUPONT'
AND PRENOM='JEAN'
ORDER BY D_EMPRUNT;

--Q6
SELECT NUMERO, CODE_PRET, ETAT
FROM LIVRE, EXEMPLAIRE
WHERE EXEMPLAIRE.ISBN = LIVRE.ISBN
AND TITRE='LE MUR';

--Q7
SELECT NUMERO, ETAT
FROM EXEMPLAIRE, LIVRE
WHERE EXEMPLAIRE.ISBN = LIVRE.ISBN
AND NUMERO<>'4112'
AND TITRE=(
    SELECT TITRE
    FROM EXEMPLAIRE, LIVRE
    WHERE EXEMPLAIRE.ISBN = LIVRE.ISBN
    AND NUMERO='4112'
    AND ETAT='BON'
);

--Q8V1
SELECT TITRE
FROM LIVRE
WHERE NOT EXISTS(
    SELECT ISBN
    FROM EXEMPLAIRE
    WHERE LIVRE.ISBN = EXEMPLAIRE.ISBN
);

--Q8V2
SELECT TITRE
FROM LIVRE
WHERE ISBN NOT IN (
    SELECT ISBN
    FROM EXEMPLAIRE
);

--Q9V1
SELECT CATEGORIE
FROM LIVRE
WHERE NOT EXISTS(
    SELECT CATEGORIE
    FROM LIVRE, EXEMPLAIRE, EMPRUNT
    WHERE LIVRE.ISBN = EXEMPLAIRE.ISBN
    AND NUMERO = NUM_EX
);

--Q9V2
SELECT CATEGORIE
FROM LIVRE
WHERE CATEGORIE NOT IN(
    SELECT CATEGORIE
    FROM EXEMPLAIRE, EMPRUNT
    WHERE NUMERO = NUM_EX
);

--Q10
SELECT COUNT(*)
FROM EMPRUNT, ABONNE
WHERE EMPRUNT.NUM_AB = ABONNE.NUM_AB
AND NOM='RENARD'
AND PRENOM='ALBERT'
AND D_RET_REEL IS NULL;

--Q11
SELECT MIN(TARIF*NVL(1-REDUC/100,1))
FROM ABONNE;

--Q12
SELECT NUMERO
FROM EXEMPLAIRE,EMPRUNT
WHERE NUMERO = NUM_EX
AND ETAT='ABIME'
AND D_RET_REEL IS NULL;

--Q13
SELECT MOT
FROM MOT_CLEF
WHERE MOT NOT IN (
    SELECT MOT
    FROM CARACTERISE
);

--Q14
SELECT COUNT(*),CATEGORIE, ABONNE.NUM_AB, ABONNE.NOM
FROM LIVRE, EXEMPLAIRE, EMPRUNT, ABONNE
WHERE ABONNE.NUM_AB = EMPRUNT.NUM_AB
AND NUMERO = NUM_EX
AND EXEMPLAIRE.ISBN = LIVRE.ISBN
GROUP BY CATEGORIE, ABONNE.NUM_AB, ABONNE.NOM
ORDER BY CATEGORIE;

--Q15
SELECT LIVRE.TITRE, AVG(PRIX)
FROM LIVRE, EXEMPLAIRE
WHERE EXEMPLAIRE.ISBN = LIVRE.ISBN
GROUP BY LIVRE.ISBN, LIVRE.TITRE
HAVING COUNT(*)>2;

--Q16
SELECT TITRE
FROM LIVRE, CARACTERISE
WHERE LIVRE.ISBN = CARACTERISE.ISBN
AND LIVRE.ISBN <> '0_8_7707_2'
AND MOT IN (
    SELECT MOT
    FROM CARACTERISE
    WHERE ISBN = '0_8_7707_2'
)
GROUP BY TITRE
HAVING COUNT(DISTINCT MOT)= (
	SELECT COUNT(MOT)
    FROM CARACTERISE
    WHERE ISBN = '0_8_7707_2'
);

--Q17
SELECT CATEGORIE
FROM LIVRE, EXEMPLAIRE, EMPRUNT, ABONNE
WHERE LIVRE.ISBN = EXEMPLAIRE.ISBN
AND NUMERO = NUM_EX
AND ABONNE.NUM_AB = EMPRUNT.NUM_AB
GROUP BY CATEGORIE
HAVING COUNT(ABONNE.NUM_AB)= (
	SELECT COUNT(*)
	FROM ABONNE
);