    --reponses questions tp2

    Q8 : 
    SELECT TABLE_NAME FROM USER_TABLES;

    Q9 : 
    PAS FAISABLE D APRES LE PROF

    Q10 : 
    SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME='ABONNE';

    Q11 : 
    SELECT COUNT(*) FROM USER_TAB_COLUMNS;

    Q12 :
    SELECT CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME LIKE 'PK%' OR  CONSTRAINT_NAME LIKE 'FK%';