SELECT *
FROM ABONNE;



ALTER TABLE ABONNE ADD(
	DATE_NAI DATE,
	TYPE_AB VARCHAR(30) CHECK(TYPE_AB IN('ADULTE','ENFANT')),
	CAT_AB VARCHAR(30) CHECK(CAT_AB IN('REGULIER','OCCASIONNEL','A PROBLEME','EXCLU'))
);

UPDATE ABONNE SET DATE_NAI=(SELECT SYSDATE-365*AGE FROM DUAL);

ALTER TABLE AUTEUR ADD(
	CONSTRAINT PK_AUTEUR PRIMARY KEY (IDAU)
);

ALTER TABLE LIVRE ADD(
	CONSTRAINT PK_LIVRE PRIMARY KEY (ISBN)
);